package com.android.shorttext;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.util.DisplayMetrics;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

public class SlangList extends Fragment {
	View v;

	/** Called when the activity is first created. */
	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
			Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		DisplayMetrics dm = new DisplayMetrics(); 
		getActivity().getWindowManager().getDefaultDisplay().getMetrics(dm);

		
		
		final int height =dm.heightPixels;
		final int width =dm.widthPixels;
		if ((height == 1280)  && (width ==800)){
			v = inflater.inflate(R.layout.slanglst_7inches, container, false);
			}else if ((height == 1024) && (width == 600)) {
				v = inflater.inflate(R.layout.slanglst_7inches, container, false);
			}
		else if ((height > 960)  && (width >730)){
			v = inflater.inflate(R.layout.slanglst_tablet, container, false);
		}else if ((height < 480)  && (width <320)){
				v = inflater.inflate(R.layout.slanglst_small, container, false);
			}
		else{
			v = inflater.inflate(R.layout.slanglst, container, false);
		}
		
		TextView tv = (TextView) v.findViewById(R.id.tv1);

		String s = "<3                           heart"
				+ "\n?                                 I have a question / I do not understand what you mean"
				+ "\n?4U                            I have a question for you"
				+ "\n;S                               Gentle warning, like ''Hmm? what did you say?''"
				+ "\n^^                               Read line / Message above"
				+ "\n<3                           Sideways heart (love, friendship)"
				+ "\n@TEOTD                  At the end of the day "
				+ "\n121                            One-to-one (private chat initiation)"
				+ "\n14AA41                     One for all, and all for one"
				+ "\n10X                            Thanks"
				+ "\n1CE                           Once"
				+ "\n1DR                           I wonder"
				+ "\n2                                To (SMS)"
				+ "\n2EZ                            Too easy"
				+ "\n2G2BT                       Too good to be true"
				+ "\n2M2H                        Too much too handle"
				+ "\n2MI                            Too much information"
				+ "\n2MOR                        Tomorrow"
				+ "\n2NTE                         Tonight"
				+ "\n4                                 For (SMS)"
				+ "\n404                             I haven't a clue / I do not know"
				+ "\n411                            Meaning 'information'"
				+ "\n4COL                         For crying out loud"
				+ "\n4EAE                          Forever and ever"
				+ "\n4NR                           Foreigner"
				+ "\n^5                               High-five"
				+ "\n511                             Too much information"
				+ "\n555                             Sobbing / crying. (Mandarin Chinese txt msgs)"
				+ ""
				+ "\n6Y                              Sexy"
				+ "\n7K                              Sick"
				+ "\n73                               Bye (amateur radio)"
				+ "\n86                               Over"
				+ "\n88                               Bye-bye (Mandarin Chinese txt msgs)"
				+ "\n88                               Hugs and kisses"
				+ "\n*s*                             Meaning 'smile'"
				+ "\n*w*                            Meaning 'wink' "
				+ "\n"
				+ "\n"
				+ "\n"
				+ "\nA"
				+ "\n"

				+ "\nA3                              Anytime, anywhere, anyplace"
				+ "\nAA                             As above / As always"
				+ "\nAAF                           As a matter of fact"
				+ "\nAAF                           As a friend"
				+ "\nAAK                          Asleep at keyboard"
				+ "\nAAK                           Alive and kicking"
				+ "\nAAMOF                     As a matter of fact"
				+ "\nAAMOI                      As a matter of interest"
				+ "\nAAP                            Always a pleasure"
				+ "\nAAR                           At any rate"
				+ "\nAATK                        Always at the keyboard"
				+ "\nABT                           About"
				+ "\nABT2                         About to"
				+ "\nABTA                         Meaning Good-bye (signoff)"
				+ "\nACD                           ALT / CONTROL / DELETE"
				+ "\nACDNT                     Accident (e-mail, Government)"
				+ "\nACK                          Acknowledge"
				+ "\nACPT                         Accept (e-mail, Government)"
				+ "\nACQSTN                   Acquisition (e-mail, Government)"
				+ "\nADAD                        Another day, another dollar"
				+ "\nADBB                        All done, bye-bye"
				+ "\nADD                          Address"
				+ "\nADR                          Address"
				+ "\nADIP                         Another day in paradise"
				+ "\nADMIN                     Administrator"
				+ "\nADMINR                  Administrator (Government)"
				+ "\nAEAP                       As early as possible"
				+ "\nAF                             April Fools"
				+ "\nAFC                          Away from computer"
				+ "\nAFAIAA                    As far as I am aware"
				+ "\nAFAIC                      As far as I am concerned"
				+ "\nAFAIK                      As far as I know"
				+ "\nAFAP                        As far as possible"
				+ "\nAFJ                           April Fool's joke"
				+ "\nAFK                          Away from keyboard"
				+ "\nAH                             At home"
				+ "\nAIGHT                       Alright"
				+ "\nAIR                            As I remember"
				+ "\nAISB                          As it should be or As I said before"
				+ "\nAISI                           As I see it"
				+ "\nAKA                          Also known as"
				+ "\nALCON                     All concerned"
				+ "\nALOL                        Actually laughing out loud"
				+ "\nAMAP                       As much as possible"
				+ "\nAMBW                      All my best wishes"
				+ "\nAML                          All my love "
				+ "\nAMOF                       As a matter of fact"
				+ "\nAOTA                        All of the above"
				+ "\nAPAC                        All praise and credit"
				+ "\nAQAP                        As quick as possible / As quiet as possible"
				+ "\nARE                           Acronym rich enviornment"
				+ "\nASIG                          And so it goes"
				+ "\nASAP                         As soon as possible"
				+ "\nA/S/L                         Age/sex/location"
				+ "\nASL                           Age/sex/location"
				+ "\nASLA                        Age/sex/location/availability"
				+ "\nAT                             At your terminal"
				+ "\nATB                           All the best"
				+ "\nATEOTD                   At the end of the day"
				+ "\nATM                          At the moment"
				+ "\nATSITS                      All the stars in the sky"
				+ "\nATSL                         Along the same line / lines"
				+ "\nAWESO                     Awesome"
				+ "\nAWOL                       Absent without leave / Away without leaving"
				+ "\nAYDY                       Are you done yet?"
				+ "\nAYEC                        At your earliest convenience"
				+ "\nAYOR                       At your own risk"
				+ "\nAYSOS                     Are you stupid or something?"
				+ "\nAYS                          Are you serious?"
				+ "\nAYT                          Are you there?"
				+ "\nAYTMTB                  And you're telling me this because"
				+ "\n"
				+ "\n"
				+ "\n"
				+ "\nB"
				+ "\n"

				+ "\nB                                Back"
				+ "\nB&                     Banned"
				+ "\nB2W                          Back to work"
				+ "\nB8                              Bait (person teased or joked with)"
				+ "\nB9                              Boss is watching"
				+ "\nB/F                             Boyfriend"

				+ "\nB/G                            Background (personal information request)"
				+ "\nB4                              Before"
				+ "\nB4N                           Bye for now"
				+ "\nBAK                          Back at the keyboard"
				+ "\nBAS                           Big a smile"
				+ "\nBASOR                     Breathing a sigh of relief"
				+ "\nBAU                          Business as usual"
				+ "\nBAY                          Back at ya"
				+ "\nBB                             Be back"
				+ "\nBB                             Bebi / Baby"
				+ "\nBBC                          Big bad challenge"
				+ "\nBBIAB                       Be back in a bit"
				+ "\nBBIAF                       Be back in a few"
				+ "\nBBIAM                      Be back in a minute"
				+ "\nBBIAS                       Be back in a sec"
				+ "\nBBL                           Be back later"
				+ "\nBBN                          Bye bye now"
				+ "\nBBS                           Be back soon"
				+ "\nBBT                           Be back tomorrow"
				+ "\nBC                             Because"
				+ "\nB/C                            Because"
				+ "\nBC                             Be cool"
				+ "\nBCNU                       Be seeing you"
				+ "\nBCOS                        Because"
				+ "\nBD                             Big deal"
				+ "\nBDAY                        Birthday"
				+ "\nB-DAY                      Birthday"
				+ "\nBDN                          Big darn number"
				+ "\nBEG                           Big evil grin"
				+ "\nBF                              Boy friend"
				+ "\nBFAW                       Best friend at work"
				+ "\nBF                              Best friend"
				+ "\nBFF                           Best friends forever"
				+ "\nBFFL                         Best friends for life"
				+ "\nBFFLNMW               Best friends for life, no matter what"
				+ "\nBFD                           Big freaking deal"
				+ "\nBFG                           Big  freaking grin"
				+ "\nBFFN                         Best friend for now"
				+ "\nBFN                           Bye for now"
				+ "\nBG                             Big grin"
				+ "\nBGWM                      Be gentle with me"
				+ "\nBHL8                         Be home late"
				+ "\nBIB                            Boss is back"
				+ "\nBIBO                         Beer in, beer out"
				+ "\nBIF                             Before I forget"
				+ "\nBIH                            Burn in hell"
				+ "\nBIL                             Brother in law"
				+ "\nBION                         Believe it or not"
				+ "\nBIOYN                      Blow it out your nose"
				+ "\nBIOYIOP                   Blow it out your I/O port"
				+ "\nBITMT                       But in the meantime"
				+ "\nBL                              Belly laugh"
				+ "\nBLNT                         Better luck next time"
				+ "\nBM                             Bite me"
				+ "\nBME                           Based on my experience"
				+ "\nBMGWL                    Busting my gut with laughter"
				+ "\nBM&Y                Between me and you"
				+ "\nBOB                           Back off *buddy*"
				+ "\nBOL                           Best of luck"
				+ "\nBOLO                        Be on the look out"
				+ "\nBOOMS                    Bored out of my skull"
				+ "\nBOTEC                      Back-of-the-envelope calculation"
				+ "\nBOSMKL                  Bending over smacking my knee laughing"
				+ "\nBOT                           Back on topic"
				+ "\nBOT                           Be on that"
				+ "\nBOYF                        Boyfriend"
				+ "\nBPLM                        Big person little mind"
				+ "\nBRB                           Be right back"
				+ "\nBRD                           Bored"
				+ "\nBRH                           Be right here"
				+ "\nBRT                           Be right there"
				+ "\nBSF                           But seriously folks"
				+ "\nBSTS                         Better safe than sorry"
				+ "\nBT                              Bite this"
				+ "\nBT                              Between technologies"
				+ "\nBTA                           But then again"
				+ "\nBTDT                         Been there, done that"

				+ "\nBTW                          By the way"
				+ "\nBTA                           But then again..."
				+ "\nBTDT                         Been there, done that"
				+ "\nBTW                          By the way"
				+ "\nBWL                          Bursting with laughter"
				+ "\nBWTHDIK                But what the heck do I know...?"
				+ "\nBWL                          Bursting with laughter"
				+ "\nBYOB                        Bring your own beer"
				+ "\nBYOC                        Bring your own computer"
				+ "\nBYTM                        Better you than me"
				+ "\n"
				+ "\n"
				+ "\n"
				+ "\nC"
				+ "\n"
				+ "\nC4N                          Ciao for now"
				+ "\nC&G                  Chuckle and grin"
				+ "\nCAD                          Control + Alt + Delete"
				+ "\nCAM                         Camera"
				+ "\nCB                             Coffee break"
				+ "\nCB                             Chat break"
				+ "\nCFS                            Care for secret?"
				+ "\nCFY                           Calling for you"
				+ "\nCIAO                         Good-bye"
				+ "\nCICO                         Coffee in, coffee out"
				+ "\nCID                            Crying in disgrace"
				+ "\nCID                            Consider it done"
				+ "\nCLAB                        Crying like a baby"
				+ "\nCM                            Call me"
				+ "\nCMB                         Call me back"
				+ "\nCMIIW                      Correct me if I'm wrong"
				+ "\nCMON                      Come on"
				+ "\nCNP                          Continued in next post"
				+ "\nCRB                          Come right back"
				+ "\nCRBT                        Crying real big tears"
				+ "\nCRS                           Can't remember *stuff*"
				+ "\nCSG                           Chuckle, snicker, grin"
				+ "\nCSL                            Can't stop laughing"
				+ "\nCT                              Can't talk"
				+ "\nCTC                           Care to chat?"
				+ "\nCTHU                        Cracking the *heck* up"
				+ "\nCU                             See you too"
				+ "\nCU                             See you"
				+ "\nCUL                           See you later"
				+ "\nCUL8ER                    See you later"
				+ "\nCUMID                     See you in my dreams"
				+ "\nCURLO                     See you around like a donut"
				+ "\nCWOT                      Complete waste of time"
				+ "\nCWYL                      Chat with you later"
				+ "\nCYA                          See ya"
				+ "\nCYAL8R                   See you later"
				+ "\nCYE                          Check your e-mail"
				+ "\nCYO                         See you online"
				+ "\n"
				+ "\n"
				+ "\nD"
				+ "\n"
				+ "\nDA                             Meaning 'The'"
				+ "\nDBAU                        Doing business as usual"
				+ "\nDC                             Disconnect"
				+ "\nDD                             Due diligence"
				+ "\nDE                             This is (amateur radio)"
				+ "\nDF                             Don't even go there"
				+ "\nDFLA                        Disenhanced four-letter acronym"
				+ "\nDGAF                        Don't give a *freak*"
				+ "\nDIIK                          Darned if I know"
				+ "\nDIS                            Did I say?"
				+ "\nDITYID                      Did I tell you I'm distressed?"
				+ "\nDIY                            Do it yourself"
				+ "\nDIKU                         Do I know you?"
				+ "\nDITYID                      Did I tell you I'm distressed?"
				+ "\nDKDC                        Don't know, don't care"
				+ "\nDL                              Dead link"
				+ "\nD/L                             Download"
				+ "\nDL                              Download"
				+ "\nDL                              Down low"
				+ "\nDLTBBB                    Don't let the bed bugs bite"
				+ "\nDM                             Doesn't matter"
				+ "\nDM                             Direct message"
				+ "\nDN                              Down"
				+ "\nDNC                           Do not compute (meaning I do not understand)"
				+ "\nDNR                           Dinner (SMS)"
				+ "\nDNT                           Don't"
				+ "\nd00d                           Dude"
				+ "\nDOM                          Dirty old man"
				+ "\nDOS                           Dozing off soon"
				+ "\nDP                              Display Picture (Yahoo Messenger Chat)"
				+ "\nDQMOT                    Don't quote me on this"
				+ "\nDR                             Didn't read"
				+ "\nDTR                           Define the relationship"
				+ "\nDTRT                         Do the right thing"
				+ "\nDTS                            Don't think so"
				+ "\nDTTD                         Don't touch that dial"
				+ "\nDUPE                         Duplicate"
				+ "\nDUR                           Do you remember?"
				+ "\nDV8                           Deviate"
				+ "\nDWB                          Don't write back"
				+ "\nDXNRY                      Dictionary"
				+ "\nDYNWUTB               Do you know what you are talking about?"
				+ "\nDYFI                          Did you find it?"
				+ "\nDYOR                        Do your own research"
				+ "\n"
				+ "\n"
				+ "\nE"
				+ "\n"
				+ "\nE                                Ecstasy"
				+ "\nE1                              Everyone"
				+ "\nE123                          Easy as one, two, three"
				+ "\nE2E                            Exchange to exchange"
				+ "\nE2E                            e-business to e-business"
				+ "\nE2E                            Employee to employee"
				+ "\nE2E                            End to end"
				+ "\nE2EG                         Ear to ear grin"
				+ "\nEAK                          Eating at keyboard"
				+ "\nEBKAC                     Error between keyboard and chair"
				+ "\nEF4T                          Effort"
				+ "\nEG                             Evil grin"
				+ "\nEI                               Eat it"
				+ "\nEIP                             Editing in progress"
				+ "\nEMA                          E-mail address"
				+ "\nEMFBI                       Excuse me for butting in"
				+ "\nEMFBI                       Excuse me for jumping in"
				+ "\nEMSG                        E-mail message"
				+ "\nENUF                         Enough"
				+ "\nEOD                           End of day"
				+ "\nEOD                           End of discussion"
				+ "\nEOL                           End of lecture"
				+ "\nEOL                           End of life"
				+ "\nEOM                          End of message"
				+ "\nEOS                           End of show"
				+ "\nEOT                           End of transmission"
				+ "\nEOT                           End of thread (end of discussion)"
				+ "\nERS2                         Eres tz / are you (Spanish SMS)"
				+ "\nES                              Erase screen"
				+ "\nETA                           Estimated time (of) arrival"
				+ "\nETLA                        Extended three-letter acronym (an FLA)"
				+ "\nEVA                          Ever"
				+ "\nEVO                          Evolution"
				+ "\nEYC                          Excitable, yet calm"
				+ "\nEZ                              Easy"
				+ "\nEZY                           Easy"
				+ "\n"
				+ "\n"
				+ "\nF"
				+ "\n"
				+ "\nF                                 Meaning female"
				+ "\nF2F                             Face to face"
				+ "\nFAAK                        Falling asleep at keyboard"
				+ "\nFAF                            Funny as *freak*"
				+ "\nFAQ                           Frequently-asked questions"
				+ "\nFBF                            Fat boy food (e.g. pizza, burgers, fries)"
				+ "\nFBM                           Fine by me"
				+ "\nFBOW                        For better or worse"
				+ "\nFC                              Fingers crossed"
				+ "\nFFS                            For *freak'*sakes"
				+ "\nFICCL                        Frankly I couldn't care a less"
				+ "\nFIIK                           *Freaked* if I know"
				+ "\nFIIOOH                      Forget it, I'm out of here"
				+ "\nFIL                              Father in law"
				+ "\nFISH                           First in, still here"
				+ "\nFIMH                          Forever in my heart"
				+ "\nFITB                           Fill in the blank"
				+ "\nFLA                            Four-letter acronym"
				+ "\nFMTYEWTK             Far more than you ever wanted to know"
				+ "\nFOMC                        Falling off my chair"
				+ "\nFOMCL                     Falling off my chair laughing"
				+ "\nFOAD                         Freak off and die"
				+ "\nFOAF                         Friend of a friend"
				+ "\nFRT                            For real though"
				+ "\nFTBOMH                   From the bottom of my heart"
				+ "\nFTW                           For the win"
				+ "\nFU                              *Freak* you"
				+ "\nFUBAR                      Fouled up beyond all recognition"
				+ "\nFUBB                         Fouled up beyond belief"
				+ "\nFUD                           Fear, Uncertainty, and Doubt"
				+ "\nFW                             Forward"
				+ "\nFWM                         Fine with me"
				+ "\nFWIW                       For what it's worth"
				+ "\nFYEO                        For your eyes only"
				+ "\nFYA                          For your amusement"
				+ "\nFYI                            For your information"
				+ "\n"
				+ "\n"
				+ "\nG"
				+ "\n"
				+ "\nG                               Grin"
				+ "\nG                               Giggle"
				+ "\nG/F                            Girlfriend"
				+ "\nG2CU                        Good to see you"
				+ "\nG2G                           Got to go"
				+ "\nG4C                           Going for coffee"
				+ "\nG9                              Genius"
				+ "\nGA                             Go ahead"
				+ "\nGAL                           Get a life"
				+ "\nGAS                           Got a second?"
				+ "\nGB                             Goodbye"
				+ "\nGBTW                       Get back to work"
				+ "\nGBU                          God bless you"
				+ "\nGDR                          Grinning, ducking, and running"
				+ "\nGFI                            Go for it"
				+ "\nGF                             Girlfriend"
				+ "\nGFN                          Gone for now"
				+ "\nGG                            Gotta Go"
				+ "\nGGMSOT                 Gotta get me some of that"
				+ "\nGGOH                      Gotta get outa Here"
				+ "\nGIGO                        Garbage in, garbage out"
				+ "\nGIAR                        Give it a rest"
				+ "\nGIGO                        Garbage in, garbage out"
				+ "\nGIRL                         Guy in real life"
				+ "\nGIWIST                     Gee, I wish I'd said that"
				+ "\nGJ                              Good job"
				+ "\nGL                             Good luck"
				+ "\nGMBA                      Giggling my butt off"
				+ "\nGMTA                      Great minds think alike"
				+ "\nGMAB                      Give me a break"
				+ "\nGMTA                      Great minds think alike"
				+ "\nGN                            Good night"
				+ "\nGNE1                        Good night everyone"
				+ "\nGNIGHT                   Good night"
				+ "\nGNITE                      Good night"
				+ "\nGNSD                       Good night, sweet dreams"
				+ "\nGOL                          Giggling out loud"
				+ "\nGOI                           Get over it"
				+ "\nGOL                          Giggling out loud"
				+ "\nGR8                           Great"
				+ "\nGRATZ                     Congratulations"
				+ "\nGRL                          Girl"
				+ "\nGRWG                      Get right with God"
				+ "\nGR&D               Grinning, running and ducking"
				+ "\nGS                             Good shot"
				+ "\nGTRM                       Going to read mail"
				+ "\nGTSY                        Glad to see you"
				+ "\nGT                             Good try"
				+ "\nGTFO                        Get the *freak* out"
				+ "\nGTG                          Got to go"
				+ "\nGTRM                       Going to read mail"
				+ "\nGTSY                        Great (or good) to see you"
				+ "\nGUD                          Good"
				+ "\nGWHTLC                  Glad we had this little chat"
				+ "\n"
				+ "\n"
				+ "\nH"
				+ "\n"
				+ "\nH                                Hug"
				+ "\nH8                              Hate"
				+ "\nH8TTU                      Hate to be you"
				+ "\nH&K                  Hug and kiss"
				+ "\nH2CUS                      Hope to see you soon"
				+ "\nHAGN                       Have a good night"
				+ "\nHAGO                       Have a good one"
				+ "\nHAG1                        Have a good one"
				+ "\nHAND                       Have a nice day"
				+ "\nHAK                          Hug and kiss"
				+ "\nHAU                          How about you?"
				+ "\nHB                             Hurry back"
				+ "\nHB                             Hug back"
				+ "\nH-BDAY                    Happy Birthday"
				+ "\nHBU                           How about you?"
				+ "\nHF                              Have fun"
				+ "\nHFAC                        Holy flipping animal crackers"
				+ "\nH-FDAY                    Happy Father's Day"
				+ "\nHHIS                          Head hanging in shame"
				+ "\nHHIS                         Hanging head in shame"
				+ "\nHIG                           How's it going"
				+ "\nHLA                           Hola / hello (Spanish SMS)"
				+ "\nH-MDAY                   Happy Mother's Day"
				+ "\nHNL                           Whole 'H' another level"
				+ "\nHOAS                         Hold on a second"
				+ "\nHP                              Hit points / Health points (online gaming)"
				+ "\nHRU                           How are you?"
				+ "\nHTH                            Hope this helps"
				+ "\nHT                              Hi there"
				+ "\nHTH                           Hope this helps"
				+ "\nHUB                           Head up butt"
				+ "\nHUYA                        Head up your *butt*"
				+ "\nHV                             Have"
				+ "\nHW                             Homework"
				+ "\n"
				+ "\n"
				+ "\nI"
				+ "\n"
				+ "\nI2                                I too (me too)"
				+ "\nIA8                             I already ate"
				+ "\nIAAA                         I am an accountant"
				+ "\nIAAD                         I am a doctor"
				+ "\nIAAL                          I am a lawyer"
				+ "\nIANAC                      I am not a crook"
				+ "\nIAC                            In any case"
				+ "\nIAE                             In any event"
				+ "\nIAO                            I am out (of here)"
				+ "\nIAW                           I agree with / In accordance with"
				+ "\nIB                               I'm back"
				+ "\nIC                               I see"
				+ "\nICAM                         I couldn't agree more"
				+ "\nICBW                         It could be worse"
				+ "\nICEDI                         I can't even discuss it"
				+ "\nICFILWU                   I could fall in love with you"
				+ "\nIDC                            I don't care"
				+ "\nIDK                            I don't know"
				+ "\nIDTS                          I don't think so"
				+ "\nIDUNNO                   I don't know"
				+ "\nIFYP                          I feel your pain"
				+ "\nIG2R                           I got to run"
				+ "\nIGHT                          I got high tonight"
				+ "\nIGN                            I (I've) got nothing"
				+ "\nIHNI                           I have no idea"
				+ "\nIHA                            I hate acronyms"
				+ "\nIHU                            I hear you"
				+ "\nIIRC                           If I recall / remember / recollect correctly"

				+ "\nIIIO                            Intel inside, idiot outside"
				+ "\nIK                              I know"
				+ "\nIKR                            I know, right"
				+ "\nILBL8                        I'll be late"

				+ "\nILU                             I love you"
				+ "\nILY                             I love you"
				+ "\nIM                              Immediate message"
				+ "\nIM                              Instant message"
				+ "\nIMAO                        In my arrogant opinion"
				+ "\nIMCO                        In my considered opinion"
				+ "\nIMHO                        In my humble opinion"
				+ "\nIMing                         Chatting with someone online"
				+ "\nIMNSHO                   In my not so humble opinion"
				+ "\nIMO                           In my opinion"
				+ "\nIMS                            I am sorry"
				+ "\nIMSB                         I am so bored"
				+ "\nIMTM                         I am the man"
				+ "\nIMU                            I miss u (you)"
				+ "\nIOMH                         In over my head"
				+ "\nIOW                           In other words"
				+ "\nIRL                             In real life"
				+ "\nITA                             I totally agree"
				+ "\nITIGBS                       I think I'm going to be sick"
				+ "\nIRMC                          I rest my case"
				+ "\nISLY                           I still love you"
				+ "\nITYK                          I thought you knew"
				+ "\nIWAWO                     I want a way out"
				+ "\nIWIAM                       Idiot wrapped in a moron"
				+ "\nIWALU                      I will always love you"
				+ "\nIYO                            In your opinion"
				+ "\nIYSS                           If you say so"
				+ "\nIYSWIM                    If you see what I mean"
				+ "\n"
				+ "\n"
				+ "\nJ"
				+ "\n"
				+ "\nj00                             You"
				+ "\nj00r                            Your"
				+ "\nJ4G                            Just for grins"
				+ "\nJAC                           Just a sec"
				+ "\nJAM                          Just a minutes"
				+ "\nJBOD                        Just a bunch of disks"
				+ "\nJFF                            Just for fun"
				+ "\nJFGI                          Just *freaking* Google it"
				+ "\nJIC                            Just in case"
				+ "\nJK                             Just kidding"
				+ "\nj/k                              Just kidding"
				+ "\nJLMK                        Just let me know"
				+ "\nJP                              Just playing"
				+ "\nJMO                          Just my opinion"
				+ "\nJTLYK                      Just to let you know"
				+ "\nJW                             Just wondering"
				+ "\n"
				+ "\n"
				+ "\nK"
				+ "\n"
				+ "\nk                                Ok"
				+ "\nK                               Okay"
				+ "\nKK                            Knock, knock"
				+ "\nKK                           Okay, Okay!"
				+ "\nk/b                             Keyboard"
				+ "\nKB                            Keyboard"
				+ "\nKDFU                       Means Cracking (K) the (D as in Da) *freak* up"
				+ "\nKEWL                      Cool"
				+ "\nKEYA                       I will key you later"
				+ "\nKEYME                    Key me when you get in"
				+ "\nKFY                          Kiss for you"
				+ "\nKIA                           Know it all"
				+ "\nKISS                         Keep it simple stupid"
				+ "\nKIT                           Keep in touch"
				+ "\nKOC                         Kiss on cheek"
				+ "\nKOTC                       Kiss on the cheek"
				+ "\nKOTL                       Kiss on the lips"
				+ "\nKPC                         Keeping parents clueless"
				+ "\nKUTGW                   Keep up the good work"
				+ "\nKWIM?                    Know what I mean?"
				+ "\n"
				+ "\n"
				+ "\nL"
				+ "\n"
				+ "\nL2G                            Like to go?"
				+ "\nL2G                            Love to go"
				+ "\nL2K                            Like to come"
				+ "\nl33t                             Elite"
				+ "\nL8R                            Later"
				+ "\nL8R G8R                   Later gator"
				+ "\nLBAY                        Laughing back at you"
				+ "\nLEMENO                  Let me know"
				+ "\nLGH                           Lets get high"
				+ "\nLHM                          Lord help me"
				+ "\nLHO                          Laughing head off"
				+ "\nLIC                            Like I care"
				+ "\nLIK                            Liquor"
				+ "\nLIMT                         Laugh in my tummy"
				+ "\nLLGB                         Love, later, God bless"
				+ "\nLERK                         Leaving easy reach of keyboard"
				+ "\nLD                              Later, dude / Long distance"
				+ "\nLDR                            Long-distance relationship"
				+ "\nLHO                           Laughing head off"
				+ "\nLLTA                          Lots and lots of thunderous applause"
				+ "\nLMAO                        Laughing my a** off"
				+ "\nLMSO                        Laughing my socks off"
				+ "\nLMFAO                     Laughing my freaking *a* off"
				+ "\nLMIRL                       Lets meet in real life"
				+ "\nLMK                          Let me know"
				+ "\nLMNK                       Leave my name out"
				+ "\nLNT                           Meaning lost in translation"
				+ "\nLOA                           List of acronyms"
				+ "\nLOL                           Lots of love"
				+ "\nLOLO                        Lots of love"
				+ "\nLOL                            Laughing out loud"
				+ "\nLOTI                          Laughing on the inside"
				+ "\nLRF                            Little rubber feet (the little pads on the bottom of displays and other equipment)"
				+ "\nLQTM                        Laughing quietly to myself"
				+ "\nLSHMBH                   Laughing so hard my belly hurts"
				+ "\nLSV                            Language, sex and violence"
				+ "\nLTD                            Living the dream"
				+ "\nLTNS                         Long time no see"
				+ "\nLTR                            Long-term relationship"
				+ "\nLULAB                       Love you like a brother"
				+ "\nLULAS                       Love you like a sister"
				+ "\nLUWAMH                 Love you with all my heart"
				+ "\nLY                              Love ya"
				+ "\nLY4E                          Love ya forever"
				+ "\nLTS                            Laughing to self"
				+ "\nLULT                         Love you long time"
				+ "\nLULZ                         Slang for LOL"
				+ "\nLVM                          Left voice mail"
				+ "\nLWOS                       Laughing without smiling"
				+ "\nLY                              Love ya"
				+ "\nLYLAS                       Love you like crazy"
				+ "\nLYLC                         Love you like a sis"
				+ "\nLYSM                        Love you so much"
				+ "\n"
				+ "\n"
				+ "\nM"
				+ "\n"

				+ "\nM8                              Mate"
				+ "\nMB                             Mamma's boy"
				+ "\nMC                             Merry Christmas"
				+ "\nMEGO                        My eyes glaze over"
				+ "\nMEH                          Shrug or shrugging shoulders"
				+ "\nMEH                          So-so / just okay"
				+ "\nMEHH                       Sigh / sighing"
				+ "\nMFI                           Mad for it"
				+ "\nMGB                         May God bless"
				+ "\nMIRL                         Meet in real life"
				+ "\nMKAY                      Mmm, okay"
				+ "\nMLM                         Give the middle finger"
				+ "\nMNC                         Mother nature calls"
				+ "\nMNSG                       Mensaje (message in Spanish)"
				+ "\nMorF                          Male or female?"
				+ "\nMOOS                       Member of the opposite sex"
				+ "\nMOSS                        Member of same sex"
				+ "\nMorF                          Male or female"
				+ "\nMOSS                        Member of the same sex"
				+ "\nMOTOS                     Member of the opposite sex"
				+ "\nMSG                           Message"
				+ "\nMTF                           More to follow"
				+ "\nMTFBWU                  May the force be with you"
				+ "\nMTF                           More to follow"
				+ "\nMUSM                       Miss you so much"
				+ "\nMUAH                       Multiple unsuccessful attempts (at / to) humor"
				+ "\nMUSM                       Miss you so much"
				+ "\nMWAH                      Meaning 'kiss' (it is is the sound made when kissing through the air)"
				+ "\nMYO                          Mind your own (business)"
				+ "\nMYOB                       Mind your own business"
				+ "\n"
				+ "\n"
				+ "\nN"
				+ "\n"
				+ "\nn00b                          Newbie"
				+ "\nN1                              Nice one"
				+ "\nN2M                          Nothing too much"
				+ "\nNADT                        Not a darn thing"
				+ "\nNALOPKT                Not a lot of people know that"
				+ "\nNANA                       Not now, no need"
				+ "\nNBD                          No big deal"
				+ "\nNE                             Any"
				+ "\nNE1                           Anyone"
				+ "\nNFM                          None for me / Not for me"
				+ "\nNFM                          Not for me"
				+ "\nNFS                           Not for sale"
				+ "\nNFW                         No *freaking* way"
				+ "\nNFW                         Not for work"
				+ "\nNFWS                       Not for work safe"
				+ "\nNIGI                          Now I get it"
				+ "\nNIMBY                     Not in my back yard"
				+ "\nNIROK                      Not in reach of keyboard"
				+ "\nNLT                           No later than"
				+ "\nNM                            Nothing much"
				+ "\nNM                            Never mind"
				+ "\nNMH                         Not much here"
				+ "\nNMU                         Not much, you?"
				+ "\nNO1                          No one"
				+ "\nNOYB                       None of your business"
				+ "\nNP                             No problem"
				+ "\nNQT                          Newly qualified teacher"
				+ "\nNADT                       Not a darn thing"
				+ "\nNFG                          No f*****g good"
				+ "\nNFW                         No feasible way"
				+ "\nNP                             No problem"
				+ "\nN/P                            No problem"
				+ "\nNRN                          No response necessary"
				+ "\nNSA                          No strings attached"
				+ "\nNSFW                       Not safe for work"
				+ "\nNSISR                       Not sure if spelled right"
				+ "\nNT                             Nice try"
				+ "\nNTHING                   Nothing (SMS)"
				+ "\nNVM                         Never mind"
				+ "\nNVR                          Never"
				+ "\nNW                           No way"
				+ "\nNWO                        No way out"
				+ "\n"
				+ "\n"
				+ "\nO"
				+ "\n"
				+ "\nO4U                          Only for you"
				+ "\nO                               Hugs"
				+ "\nO                               Over"
				+ "\nOA                            Online auctions"
				+ "\nOATUS                     On a totally unrelated subject"
				+ "\nOB                             Oh baby"
				+ "\nOB                             Oh brother"
				+ "\nOI                              Operator indisposed"
				+ "\nOIC                            Oh, I see"
				+ "\nOLL                           Online love"
				+ "\nOIB                            Oh, I'm back"
				+ "\nOJ                              Only joking"
				+ "\nOL                             Old lady"
				+ "\nOM                            Old man"
				+ "\nOM                            Oh, my"
				+ "\nOMG                         Oh my God"
				+ "\nOMGYG2BK            Oh my God, you got to be kidding"
				+ "\nOMW                        On my way"
				+ "\nONL                          Online"
				+ "\nOMG                         Oh my God"
				+ "\nOTF                           Off the floor"
				+ "\nOTOH                        On the other hand"
				+ "\nOTTOMH                  Off the top of my head"
				+ "\nOO                             Over and out"
				+ "\nOOC                          Out of character"
				+ "\nOOH                          Out of here"
				+ "\nOOTD                        One of these days"
				+ "\nOOTO                        Out of the office"
				+ "\nOP                              On phone"
				+ "\nORLY                        Oh really?"
				+ "\nOT                             Off topic (discussion forums)"
				+ "\nOTB                           Off to bed"
				+ "\nOTFL                         On the floor laughing"
				+ "\nOTL                           Out to lunch"
				+ "\nOTOH                        On the other hand"
				+ "\nOTP                           On the phone"
				+ "\nOTT                           Over the top"
				+ "\nOTTOMH                  Off the top of my head"
				+ "\nOTW                          Off to work"
				+ "\nOVA                          Over"
				+ "\nOYO                          On your own"
				+ "\n"
				+ "\n"
				+ "\nO"
				+ "\n"
				+ "\nP2P                            Parent to parent"
				+ "\nP2P                            Peer to peer"
				+ "\nPANS                        Pretty awesome new stuff"
				+ "\nPAW                          Parents are watching"
				+ "\nPCMCIA                   People can't master computer industry acronyms"
				+ "\nPCM                          Please call me"
				+ "\nPDA                           Public display of affection"
				+ "\nPDH                           Pretty darn happy"
				+ "\nPDS                           Please don't shoot"
				+ "\nPDQ                          Pretty darn quick"
				+ "\nPEBCAK                   Problem exists between chair and keyboard"
				+ "\nPEEPS                       People"
				+ "\nPFT                           Pretty *freaking* tight"
				+ "\nPIC                            Picture"
				+ "\nPIR                            Parents in room"
				+ "\nPISS                          Put in some sugar"
				+ "\nPIBKAC                    Problem is between keyboard and chair"
				+ "\nPITA                          Pain in the ass"
				+ "\nPL8                            Plate"
				+ "\nPLD                           Played"
				+ "\nPLMK                       Please let me know"
				+ "\nPLS                           Please"
				+ "\nPLU                           People like us"
				+ "\nPLZ                            Please"
				+ "\nPM                             Private Message"
				+ "\nPMFI                         Pardon me for interrupting"
				+ "\nPMFJI                       Pardon me for jumping in"
				+ "\nPM                             Private message"
				+ "\nPOAHF                     Put on a happy face"
				+ "\n::POOF::                    Goodbye (leaving the room)"
				+ "\nPOTS                        Plain old telephone service"
				+ "\nPOAHF                     Put on a happy face"
				+ "\nPOS                           Parent over shoulder"
				+ "\nPOV                          Point of view"
				+ "\nPOV                          Privately owned vehicle"
				+ "\nPPL                           People"
				+ "\nPPU                           Pending pick-up"
				+ "\nPROLLY                   Probably"
				+ "\nPROGGY                  Computer program"
				+ "\nPRON                       Pornography"
				+ "\nPRT                           Party"
				+ "\nPRW                          People/parents are watching"
				+ "\nPSOS                        Parent standing over shoulder"
				+ "\nPSP                           Playstation Portable"
				+ "\nPTL                           Praise the Lord"
				+ "\nPTMM                       Please tell me more"
				+ "\nPU                             That stinks!"
				+ "\nPWN                         Own"
				+ "\nPXT                           Please explain that"
				+ "\nPZ                              Peace"
				+ "\nPZA                           Pizza"

				+ "\n"
				+ "\n"
				+ "\nQ"
				+ "\n"

				+ "\nQ                               Queue"
				+ "\nQFE                          Question for everyone"
				+ "\nQFI                           Quoted for idiocy"
				+ "\nQFI                           Quoted for irony"
				+ "\nQIK                           Quick"
				+ "\nQL                             Quit laughing"
				+ "\nQQ (qq)                     Crying eyes"
				+ "\nQQ                            Quick question"
				+ "\nQSL                           Reply"
				+ "\nQSO                          Conversation"
				+ "\nQT                             Cutie"
				+ "\nQTPI                         Cutie pie"

				+ "\n"
				+ "\n"
				+ "\nR"
				+ "\n"

				+ "\nR8                              Rate (SMS)"
				+ "\nRBAY                        Right back at you"
				+ "\nRIP                             Rest in peace"
				+ "\nRL                              Real life"
				+ "\nRLY                           Really"
				+ "\nRL                              Real life"
				+ "\nRME                          Rolling my eyes"
				+ "\nRMLB                        Read my lips baby"
				+ "\nRMMM                      Read my mail man"
				+ "\nROR                           Raffing out roud"
				+ "\nROTFL                       Rolling on the floor laughing"
				+ "\nROFL                         Rolling on floor laughing"
				+ "\nROTFLMAO              Rolling on the floor laughing my a** off"
				+ "\nROFLMAO                Rolling on the floor, laughing my *butt* off"
				+ "\nROFLCOPTER          Rolling on floor laughing and spinning around"
				+ "\nROTFLUTS               Rolling on the floor laughing unable to speak"
				+ "\nRPG                           Role-playing games"
				+ "\nRSN                           Real soon now"
				+ "\nRT                              Real time"
				+ "\nRTBS                         Reason to be single"
				+ "\nRTFM                        Read the *freaking* manual"
				+ "\nRTFQ                         Read the *freaking* question"
				+ "\nRTNTN                      Retention (e-mail, Government)"
				+ "\nRTRMT                      Retirement (e-mail, Government)"
				+ "\nRTSM                        Read the stupid manual"
				+ "\nRU                             Are you?"
				+ "\nRUMOF                    Are you male or female?"
				+ "\nRUT                           Are you there?"
				+ "\nRUOK                       Are you okay?"
				+ "\nRX                             Regards"
				+ "\nRW                            Real world"
				+ "\nRX                             Meaning drugs or prescriptions"
				+ "\nRYB                           Read your Bible"
				+ "\nRYS                           Read your screen"
				+ "\nRYS                           Are you single?"
				+ "\nRYO                           Roll your own"

				+ "\n"
				+ "\n"
				+ "\nS"
				+ "\n"

				+ "\nS^                               S'up - what's up"
				+ "\nSH^                            Shut up"
				+ "\nS2R                            Send to receive"
				+ "\nS2S                            Sorry to say"
				+ "\nS4L                            Spam for life"
				+ "\nSAL                           Such a laugh"
				+ "\nSBT                            Sorry 'bout that"
				+ "\nSC                              Stay cool"
				+ "\nSDMB                        Sweet dreams, my baby"
				+ "\nSETE                          Smiling ear to ear"
				+ "\nSF                               Surfer-friendly"
				+ "\nSFAIK                        So far as I know"
				+ "\nSH                              Same here"
				+ "\nSHCOON                  Shoot hot coffee out of nose"
				+ "\nSHID                          Slaps head in disgust"
				+ "\nSHID                          Slapping head in disgust"
				+ "\nSICNR                       Sorry, I could not resist"
				+ "\nSIG2R                        Sorry, I got to run"
				+ "\nSIHTH                       Stupidity is hard to take"
				+ "\nSIMYC                      Sorry I missed your call"
				+ "\nSIR                             Strike it rich"
				+ "\nSIS                             Snickering in silence"
				+ "\nSIT                             Stay in touch"
				+ "\nSK8                            Skate"
				+ "\nSK8NG                      Skating"
				+ "\nSK8R                         Skater"
				+ "\nSLAP                         Sounds like a plan"
				+ "\nSMHID                      Scratching my head in disbelief"
				+ "\nSNAFU                      Situation normal all fouled up"
				+ "\nSNERT                       Snot nosed egotistical rude teenager"
				+ "\nSN                              Situation normal"
				+ "\nSO                              Significant other"
				+ "\nS'OK                          It is okay"

				+ "\nSOL                           Sooner or later"
				+ "\nSOMY                       Sick of me yet?"
				+ "\nSorG                          Straight or Gay?"
				+ "\nSOS                           Emergency / help"
				+ "\nSOT                           Short of time"
				+ "\nSOTMG                     Short of time, must go"
				+ "\nSOWM                      Someone with me"
				+ "\nSO                             Significant other"
				+ "\nSOL                           Smilling out loud or sh*t out of luck"
				+ "\nSOMY                       Sick of me yet?"

				+ "\nSOT                           Short on time"
				+ "\nSOTMG                     Short on time must go"
				+ "\nSPK                           Speak (SMS)"
				+ "\nSRSLY                       Seriously"
				+ "\nSPST                          Same place, same time"

				+ "\nSPTO                         Spoke to"
				+ "\nSQ                             Square"
				+ "\nSRY                           Sorry"
				+ "\nSS                              So sorry"
				+ "\nSSDD                        Same stuff, different day"
				+ "\nSSIF                          So stupid it's funny"
				+ "\nSSINF                       So stupid it's not funny"
				+ "\nSTW                          Search the Web"
				+ "\nST&D                Stop texting and drive"
				+ "\nSTFU                         Shut the *freak* up"
				+ "\nSTR8                         Straight"
				+ "\nSTW                          Search the Web"
				+ "\nSUITM                      See you in the morning"
				+ "\nSUL                           See you later"
				+ "\nSUP                           What's up?"
				+ "\nSUX                          Sucks / it sucks"
				+ "\nSU                             Shut up"
				+ "\nSUAKM                    Shut up and kiss me"
				+ "\nSWAK                      Sent (or sealed) with a kiss"
				+ "\nSWALK                    Sealed (or sealed) with a loving kiss"
				+ "\nSWAT                       Scientific wild *butt* guess"
				+ "\nSWL                          Screaming with laughter"
				+ "\nSWMBO                   She who must be obeyed. (wife or partner)"
				+ "\nSWAG                       Stupid wild a** guess"
				+ "\nSWAK                       Sealed with a kiss"
				+ "\nSWL                          Screaming with laughter"
				+ "\nSYL                           See you later"
				+ "\nSYS                           See you soon"

				+ "\n"
				+ "\n"
				+ "\nT"
				+ "\n"

				+ "\nT+                              Think positive"
				+ "\nT4BU                         Thanks for being you"
				+ "\nT:)T                            Think happy thoughts"
				+ "\nTA                             Thanks a lot"
				+ "\nTA                             Thanks again"
				+ "\nTAFN                        That's all for now"
				+ "\nTAM                          Tomorrow a.m."
				+ "\nTANK                       Meaning really strong"
				+ "\nTANKED                  Owned"
				+ "\nTANKING                Owning"
				+ "\nTARFU                      Things are really fouled up."
				+ "\nTAU                          Thinking about you"
				+ "\nTAUMUALU            Thinking about you miss you always love you"
				+ "\nTAFN                        That's all for now"
				+ "\nTANSTAAFL            There ain't no such thing as a free lunch"
				+ "\nTBC                           To be continued"
				+ "\nTBD                           To be determined"
				+ "\nTBH                           To be honest"
				+ "\nTB4U                         Too bad for you"
				+ "\nTBL                            Text back later"
				+ "\nTC                              Take care"
				+ "\nTCB                           Take care of business"
				+ "\nTCOY                        Take care of yourself"
				+ "\nTFS                            Thanks for sharing"
				+ "\nTGIF                          Thank God it's Friday"
				+ "\nTHX                           Thanks"
				+ "\nTHNX                        Thanks"
				+ "\nTHNQ                       Thank you (SMS)"
				+ "\nTHT                           Think happy thoughts"
				+ "\nTILII                          Tell it like it is"
				+ "\nTIA                            Thanks in advance"
				+ "\nTIAD                         Tomorrow is another day"
				+ "\nTIC                            Tongue-in-cheek"
				+ "\nTILIS                         Tell it like it is"
				+ "\nTLK2UL8R               Talk to you later"
				+ "\nTL                              Too long"
				+ "\nTLA                           Three-letter acronym"
				+ "\nTTYAFN                   Talk to you awhile from now"
				+ "\nTLK2UL8R               Talk to you later"
				+ "\nTMI                           Too much information"
				+ "\nTMB                          Text me back"
				+ "\nTMI                           Too much information"
				+ "\nTMOT                       Trust me on this"
				+ "\nTMTH                       Too much to handle"
				+ "\nTMWFI                     Take my word for it"
				+ "\nTNSTAAFL              There's no such thing as a free lunch"
				+ "\nTNT                           Till next time"
				+ "\nTOPCA                     Til our paths cross again (early Celtic chat term)"
				+ "\nTOY                          Thinking of you"
				+ "\nTOJ                           Tears of joy"
				+ "\nTOS                          Terms of service"
				+ "\nTOU                          Thinking of you"
				+ "\nTOY                          Thinking of you"
				+ "\nTPM                          Tomorrow p.m."
				+ "\nTPTB                         The powers that be"
				+ "\nTQ                             Te quiero / I love you (Spanish SMS)"
				+ "\nTSH                           Tripping so hard"
				+ "\nTSNF                         That's so not fair"
				+ "\nTSTB                         The sooner, the better"
				+ "\nTTLY                         Totally"

				+ "\nTTTT                         These things take time"
				+ "\nTTUL                         Talk to you later"
				+ "\nTTG                           Time to go"
				+ "\nTTFN                         Ta-Ta for now"
				+ "\nTTT                            Thought that, too (when someone types in what you were about to type)"
				+ "\nTTYL                         Talk to you later"
				+ "\nTTYS                         Talk to you soon"
				+ "\nTU                             Thank you"
				+ "\nTWSS                        That's what she said"
				+ "\nTY                             Thank you"
				+ "\nTYFYC                      Thank you for your comment"
				+ "\nTYS                           Told you so"
				+ "\nTYT                           Take your time"
				+ "\nTYSO                        Thank you so much"
				+ "\nTYVM                       Thank you very much"
				+ "\n"
				+ "\n"
				+ "\nU"
				+ "\n"

				+ "\n^URS                         Up yours"
				+ "\nUAPITA                    You're a pain in the a**"
				+ "\nUAF                          Until further notice"
				+ "\nUCMU                      You crack me up"
				+ "\nUDI                           Unidentified drinking injury (bruise, scratch, ache and so on)"
				+ "\nUDM                         You the man"
				+ "\nUDS                          Ugly domestic scene"
				+ "\nUFN                          Until further notice"
				+ "\nUGTBK                     You've got to be kidding"
				+ "\nUKTR                       You know that's right"
				+ "\nUL                             Upload"
				+ "\nU-L                            You will"
				+ "\nUNA                          Use no acronyms"
				+ "\nUN4TUN8                Unfortunate"
				+ "\nUNBLEFBLE            Unbelievable"
				+ "\nUNCRTN                  Uncertain"
				+ "\nUNPC                        Not politically correct"
				+ "\nUOK                          Are you ok?"
				+ "\nUR                             Your / You're"
				+ "\nUR2YS4ME              You are too wise for me"
				+ "\nURA*                        You are a star"
				+ "\nURH                          You are hot"
				+ "\nURL                           Uniform Resource Locator"

				+ "\nURSKTM                  You are so kind to me"
				+ "\nURTM                       You are the man"
				+ "\nURW                         You are welcome"
				+ "\nUSBCA                     Until something better comes along"
				+ "\nUSU                          Usually"
				+ "\nUT2L                        You take too long"
				+ "\nUV                            Unpleasant visual"
				+ "\nUW                           You're welcome"
				+ "\n"
				+ "\n"
				+ "\nV"
				+ "\n"

				+ "\nVBS                           Very big smile"
				+ "\nVEG                           Very evil grin"
				+ "\nVFF                           Very freaking funny"
				+ "\nVFM                          Value for money"
				+ "\nVGC                          Very good condition"
				+ "\nVIP                            Very important person"
				+ "\nVM                            Voice mail"
				+ "\nVN                             Very nice"
				+ "\nVRY                          Very"
				+ "\nVSC                          Very soft chuckle"
				+ "\nVSF                           Very sad face"
				+ "\nVBG                          Very big grin"

				+ "\n"
				+ "\n"
				+ "\nW"
				+ "\n"

				+ "\nW@                          What?"
				+ "\nW/                             With"
				+ "\nW/B                           Welcome back"
				+ "\nW3                            World wide web / web address"
				+ "\nWWW                       World wide web / web address"
				+ "\nW8                            Wait"
				+ "\nWAG                         Wild a** guess"
				+ "\nWAYD                      What are you doing"
				+ "\nWAH                         Working at home"
				+ "\nWAJ                          What a jerk"
				+ "\nWAM                        Wait a minute"
				+ "\nWAN2                       Want to? (SMS)"

				+ "\nWAN2TLK               Want to talk"
				+ "\nWAREZ                     Pirated"
				+ "\nWAS                         Wait a second"
				+ "\nWAS                         Wild *a* guess"
				+ "\nWAWA                     Where are we at?"
				+ "\nWAYF                      Where are you from?"
				+ "\nWB                            Welcome back"
				+ "\nWBS                          Write back soon"
				+ "\nW/B                           Write back"
				+ "\nWBU                         What about you?"
				+ "\nWC                            Welcome"
				+ "\nWC                            Who cares"
				+ "\nWCA                         Who cares anyway"
				+ "\nWDALYIC                Who died and left you in charge"
				+ "\nWDYK                      What do you know?"
				+ "\nWDYT                       What do you think?"
				+ "\nWE                            Whatever"
				+ "\nW/E                           Whatever"
				+ "\nW/END                     Weekend"
				+ "\nWFM                         Works for me"
				+ "\nWIBNI                      Wouldn't it be nice if"
				+ "\nWH5                         Who, what, when, where, why"
				+ "\nWIBNI                      Wouldn't it be nice if"
				+ "\nWIIFM                     What's in it for me?"
				+ "\nWISP                        Winning is so pleasurable"
				+ "\nWITP                        What is the point?"
				+ "\nWITW                       What in the world"
				+ "\nWIU                          Wrap it up"
				+ "\nWK                           Week"
				+ "\nWKD                        Weekend"
				+ "\nWL                            Whatta loser"
				+ "\nW/O                          Without"
				+ "\nWOMBAT                Waste of money, brains, and time"
				+ "\nWRT                         With regard to"
				+ "\nWRK                         Work"
				+ "\nWRU@                     Where are you at?"
				+ "\nWRUD                      What are you doing?"
				+ "\nWTF                          What the *freak* ?"
				+ "\nWTFE                       What the *freak* ever"
				+ "\nWTG                         Way to go"
				+ "\nWTGP                       Want to go private (talk out of public chat area)"
				+ "\nWTH                         What the heck?"
				+ "\nWTM                        Who's the man?"
				+ "\nWT?                           What the? / who the?"
				+ "\nWTG                          Way to go!"
				+ "\nWTGP?                      Want to go private?"
				+ "\nWU?                          What's up?"
				+ "\nWU                            What's up?"
				+ "\nWUW                        What do (you) want?"
				+ "\nWUU2                       What are you up to?"
				+ "\nWUF?                        Where are you from?"
				+ "\nWWNC                     Will wonders never cease"
				+ "\nWWYC                     Write when you can"
				+ "\nWYCM                      Will you call me?"
				+ "\nWYD                         What (are) you doing?"
				+ "\nWYGAM                   When you get a minute"
				+ "\nWYHAM                   When you have a minute"
				+ "\nWYLEI                      When you least expect it"
				+ "\nWYWH                     Wish you were here"
				+ "\nWYSITWIRL            What you see is totally worthless in real life!"
				+ "\nWYSIWYG               What you see is what you get"

				+ "\n"
				+ "\n"
				+ "\nX"
				+ "\n"
				+ "\nX-1-10                       Exciting"
				+ "\nX                                Kiss"
				+ "\nX!                               A typical woman"
				+ "\nXD                             Really hard laugh (where D is a smiley mouth)"
				+ "\nXD                             Devilish smile"
				+ "\nXME                          Excuse Me"
				+ "\nXOXOXO                 Hugs & Kisses"
				+ "\nXLNT                        Excellent"
				+ "\nXLR8                         Accelerate / going faster"
				+ "\nXYL                           Ex-young lady, meaning wife. (amateur radio)"
				+ "\nXYZ                           Examine your zipper"

				+ "\n"
				+ "\n"
				+ "\nY"
				+ "\n"

				+ "\nY?                              Why?"
				+ "\nY                                Yawn"
				+ "\nY2K                           You're too kind"
				+ "\nYA                             Your"
				+ "\nYAA                          Yet another acronym"
				+ "\nYABA                       Yet another bloody acronym"
				+ "\nYARLY                     Ya, really?"
				+ "\nYBIC                         Your brother in Christ"
				+ "\nYBS                          You'll be sorry"
				+ "\nYCDBWYCID          You can't do business when your computer is down"
				+ "\nYCHT                       You can have them"
				+ "\nYCLIU                      You can look it up"
				+ "\nYCMU                      You crack me up"
				+ "\nYF                             Wife"
				+ "\nYG                            Young gentleman"
				+ "\nYGTBKM                 You've got to be kidding me"
				+ "\nYHBW                      You have been warned"
				+ "\nYHL                          You have lost"
				+ "\nYIU                           Yes, I understand"
				+ "\nYKW                        You know what"
				+ "\nYKWYCD                You know what you can do"
				+ "\nYL                             Young lady"
				+ "\nYMMV                     Your mileage may vary"
				+ "\nYNK                         You never know"
				+ "\nYR                             Your"
				+ "\nYR                             Yeah right"
				+ "\nYRYOCC                  You're running your own cuckoo clock"
				+ "\nYSIC                         Your sister in Christ"
				+ "\nYSYD                        Yeah sure you do"
				+ "\nYT                              You there?"
				+ "\nYTTL                         You take too long"
				+ "\nYTG                           You're the greatest"
				+ "\nYWHOL                    Yelling 'woohoo'out loud"
				+ "\nYWSYLS                   You win some, you lose some"
				+ "\nYYSSW                     Yeah, yeah, sure, sure, whatever"
				+ "\nYBS                           You'll be sorry"
				+ "\nYMMV                      Your mileage may vary."
				+ "\nYW                            You're welcome"

				+ "\n" 
				+ "\n" 
				+ "\nZ"
				+ "\n"

				+ "\nZ                                Zero"
				+ "\nZ                                Going to bed/sleep"
				+ "\nZ                                Said"
				+ "\nZ%                             Zoo"
				+ "\nZH                             Sleeping Hour"
				+ "\nZOT                           Zero tolerance"
				+ "\nZUP                           What's up?"
				+ "\nZZZZ                         Sleeping / bored"

		;

		tv.setText(s);

		return v;
		// TODO Auto-generated method stub
	}
}
